build_script:
- ps: >-
    $version = (Get-Content .\src\CloudNsLib\project.json | ConvertFrom-Json).version

    Update-AppveyorBuild -Version "$version build $env:APPVEYOR_BUILD_NUMBER"
- ps: >-
    # Core

    dotnet restore
- ps: >-
    # Library

    dotnet pack -c Release -o Nuget\ src\CloudNsLib
- ps: >-
    # Utilities

    dotnet build -c Release src\TestApplication
- ps: >-
    # Tests

    dotnet build -c Release src\CloudNsLibTests
environment:
  CLOUDNS_API:
    secure: 45D+okErPGmUgCN5DjXUj1GBOvkFHDWjM63Vs+eh0q4=
test_script:
- cmd: dotnet test -c Release src\CloudNsLibTests
artifacts:
- path: Nuget\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: dgfUEGXULcqCTyNcS6UEDK8BCBi8y+M2+d4IFjnb3Gf9DqV34fMSp1XjxJg2AVRC
  on:
    branch: nuget